{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1a512dd3-1bef-488b-aa44-205870856130",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== Attribution Language 분포 ===\n",
      "AttributionLanguage\n",
      "state     106\n",
      "action     39\n",
      "other      15\n",
      "Name: count, dtype: int64\n",
      "\n",
      "총 violations: 160\n",
      "\n",
      "state: 106 (66.2%)\n",
      "action: 39 (24.4%)\n",
      "other: 15 (9.4%)\n",
      "\n",
      "=== ResponsibilitySubject 분포 ===\n",
      "ResponsibilitySubject\n",
      "Firm                  159\n",
      "QualityControlUnit      1\n",
      "Name: count, dtype: int64\n",
      "\n",
      "=== action 분류 확인 (검토용) ===\n",
      "    ViolationID                                                                                                               ViolationText AttributionLanguage\n",
      "14           V3                                                                         failure to investigate discrepancies and complaints              action\n",
      "22           V2                                                             failure to thoroughly investigate product defects and complaint              action\n",
      "24           V1                                                                         failure to adequately investigate OOS assay results              action\n",
      "25           V2                                                      failure to follow quality control unit procedures for document control              action\n",
      "26           V1                         failure to verify identity and quality of incoming components / reliance on unverified supplier COA              action\n",
      "35           V3                                                     failure to adequately investigate nonconforming products and complaints              action\n",
      "36           V4                                           failure to follow quality control unit procedures and change control requirements              action\n",
      "42           V1                                                                         failure to perform finished product release testing              action\n",
      "43           V2                                                                                 failure to follow stability testing program              action\n",
      "47           V2                                            failure to adequately investigate manufacturing deviations and foreign particles              action\n",
      "55           V2                                         failure to adequately investigate HEPA filter failures and potential product impact              action\n",
      "57           V1                                         failure to establish suitability of sterility and in-process bioburden test methods              action\n",
      "60           V1                                      failure to adequately investigate dissolution OOS results and implement effective CAPA              action\n",
      "63           V2                                failure to adequately investigate OOS assay results and inappropriate product specifications              action\n",
      "68           V3                                          failure of quality unit to establish and enforce adequate procedures and oversight              action\n",
      "69           V1                           failure to perform finished drug product testing for identity and strength prior to batch release              action\n",
      "70           V2                                failure to perform identity testing for incoming active pharmaceutical ingredient components              action\n",
      "74           V3                                 failure to test incoming components for identity, impurities, purity, strength, and quality              action\n",
      "75           V1                                     failure to perform finished product identity and potency testing prior to batch release              action\n",
      "76           V2                                 failure to perform incoming component identity testing and qualify supplier COA reliability              action\n",
      "81           V4                                        failure to document and investigate purified water system monitoring and OOS results              action\n",
      "91           V2                  failure to adequately investigate OOS potency results and inappropriate retesting to justify batch release              action\n",
      "94           V3                       failure to adequately investigate microbial contamination, complaints, and recurring lot code defects              action\n",
      "100          V5                                   failure to validate or verify analytical test methods for raw materials and drug products              action\n",
      "101          V1                                                failure to adequately investigate OOS viscosity and specific gravity results              action\n",
      "106          V2                 failure to test incoming components and qualify supplier COA reliability, including component water control              action\n",
      "107          V3                                                     failure to support expiration dating with appropriate stability testing              action\n",
      "113          V1                             failure to perform identity testing of incoming components and qualify supplier COA reliability              action\n",
      "114          V2              failure to perform finished product identity, strength, impurity, and microbial testing prior to batch release              action\n",
      "117          V2                                           failure to adequately investigate and document out-of-specification (OOS) results              action\n",
      "118          V3                             failure to perform identity testing of incoming components and qualify supplier COA reliability              action\n",
      "123          V2                                                         failure to perform adequate identity testing of incoming components              action\n",
      "126          V2                                    failure to perform finished product potency and microbiological testing prior to release              action\n",
      "127          V3                             failure to perform identity testing of incoming components and qualify supplier COA reliability              action\n",
      "131          V4                                    failure to perform adequate microbiological release testing and growth promotion testing              action\n",
      "134          V2                     failure to maintain manufacturing buildings in a good state of repair and protect against contamination              action\n",
      "144          V1                                              failure to perform identity and strength testing prior to drug product release              action\n",
      "147          V1  failure to perform adequate batch-specific microbiological release testing and supported expiry-related quality evaluation              action\n",
      "154          V3                                                             failure to perform adequate batch release and sterility testing              action\n",
      "\n",
      "저장 완료: fda_warning_letters_coded.xlsx\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# ── 1. 데이터 로드 ──────────────────────────────────────────────────────────\n",
    "# 엑셀 파일명 바꿔줘\n",
    "df = pd.read_excel(\"FDA_Warning Letter.xlsx\")\n",
    "\n",
    "# ── 2. Attribution Language 분류 함수 ────────────────────────────────────────\n",
    "def classify_attribution(text):\n",
    "    if pd.isna(text):\n",
    "        return \"other\"\n",
    "    text_lower = text.lower().strip()\n",
    "    \n",
    "    # action: \"failure to\"로 시작하는 패턴\n",
    "    action_patterns = [\n",
    "        \"failure to\",\n",
    "        \"failed to\",\n",
    "        \"failure of\",\n",
    "    ]\n",
    "    \n",
    "    # state: \"inadequate\"로 시작하는 패턴\n",
    "    state_patterns = [\n",
    "        \"inadequate\",\n",
    "        \"lack of\",\n",
    "        \"incomplete\",\n",
    "        \"insufficient\",\n",
    "        \"absence of\",\n",
    "        \"missing\",\n",
    "        \"no evidence\",\n",
    "        \"fabrication of\",  # data integrity 관련\n",
    "    ]\n",
    "    \n",
    "    for p in action_patterns:\n",
    "        if text_lower.startswith(p):\n",
    "            return \"action\"\n",
    "    \n",
    "    for p in state_patterns:\n",
    "        if text_lower.startswith(p):\n",
    "            return \"state\"\n",
    "    \n",
    "    # 시작이 아니라 포함인 경우도 체크\n",
    "    if \"failure to\" in text_lower or \"failed to\" in text_lower:\n",
    "        return \"action\"\n",
    "    if \"inadequate\" in text_lower:\n",
    "        return \"state\"\n",
    "    \n",
    "    return \"other\"\n",
    "\n",
    "# ── 3. 분류 적용 ──────────────────────────────────────────────────────────────\n",
    "df[\"AttributionLanguage\"] = df[\"ViolationText\"].apply(classify_attribution)\n",
    "\n",
    "# ── 4. 결과 확인 ──────────────────────────────────────────────────────────────\n",
    "print(\"=== Attribution Language 분포 ===\")\n",
    "print(df[\"AttributionLanguage\"].value_counts())\n",
    "print()\n",
    "print(f\"총 violations: {len(df)}\")\n",
    "print()\n",
    "\n",
    "# 퍼센트\n",
    "dist = df[\"AttributionLanguage\"].value_counts()\n",
    "total = len(df)\n",
    "for k, v in dist.items():\n",
    "    print(f\"{k}: {v} ({v/total*100:.1f}%)\")\n",
    "\n",
    "print()\n",
    "print(\"=== ResponsibilitySubject 분포 ===\")\n",
    "print(df[\"ResponsibilitySubject\"].value_counts())\n",
    "\n",
    "# ── 5. 검토용 — action으로 분류된 것들 확인 ──────────────────────────────────\n",
    "print()\n",
    "print(\"=== action 분류 확인 (검토용) ===\")\n",
    "action_df = df[df[\"AttributionLanguage\"] == \"action\"][[\"ViolationID\", \"ViolationText\", \"AttributionLanguage\"]]\n",
    "print(action_df.to_string())\n",
    "\n",
    "# ── 6. 저장 ──────────────────────────────────────────────────────────────────\n",
    "df.to_excel(\"fda_warning_letters_coded.xlsx\", index=False)\n",
    "print()\n",
    "print(\"저장 완료: fda_warning_letters_coded.xlsx\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d5095961-d761-4949-8827-2314c7020a90",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== Attribution Language 분포 ===\n",
      "state: 106개 (66.2%)\n",
      "action: 39개 (24.4%)\n",
      "other: 15개 (9.4%)\n",
      "\n",
      "총 violations: 160\n",
      "\n",
      "=== ResponsibilitySubject 분포 ===\n",
      "ResponsibilitySubject\n",
      "Firm                  159\n",
      "QualityControlUnit      1\n",
      "Name: count, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.read_excel(\"fda_warning_letters_coded.xlsx\")\n",
    "\n",
    "print(\"=== Attribution Language 분포 ===\")\n",
    "dist = df[\"AttributionLanguage\"].value_counts()\n",
    "total = len(df)\n",
    "for k, v in dist.items():\n",
    "    print(f\"{k}: {v}개 ({v/total*100:.1f}%)\")\n",
    "\n",
    "print(f\"\\n총 violations: {total}\")\n",
    "\n",
    "print(\"\\n=== ResponsibilitySubject 분포 ===\")\n",
    "print(df[\"ResponsibilitySubject\"].value_counts())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e3c961d-8397-4f26-adef-4b2a7ffbbd69",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
